### PR TITLE
ISPN-5288 Options for configuring various providers in cloud cache store

### PR DESCRIPTION
**Pull request by vjuranek**
https://issues.jboss.org/browse/ISPN-5288

### CODE REVIEW

**Comment by vjuranek** [comment]
Tested (besides default transient store) with Amazon S3 and Filesystem providers. OpenStack Swift testing is still missing.

**Comment by galderz** [comment]
Hey @vjuranek, thanks a lot for working on this.

I'm not sure about "overrides", whether that's how we want to pass in provider specific properties. @tristantarrant @pferraro, thoughts?

**Comment by vjuranek** [comment]
@galderz well, that's not my idea, that's from JCoulds API and if you want to be able to configure some providers, you can either use this or define few properties which we would support and thus limit which providers user can use and to which extend it can be configured (e.g. in case of file provider, AFAIK there isn't any other way how to specify base directory other then passing `[org.jclouds.filesystem.reference.FilesystemConstants.PROPERTY_BASEDIR, "test-dir"]` into overrides).

**Comment by galderz** [comment]
@vjuranek I checked with @tristantarrant and it's all good :), I'll integrate asap, thanks!

**Pull request closed without merging**
