### PR TITLE
ISPN-8748 Upgrade to support Infinispan 9.x

### PR DESCRIPTION
**Pull request by tristantarrant**
- Add example to documentation
- Test multiple schema versions
- Upgrade to JClouds 2.1.2

https://issues.jboss.org/browse/ISPN-8748

### CODE REVIEW

**Comment by vjuranek** [comment]
Cache store itself works with `s3`, but tests fail with some auth issue (when run against `s3`) ... looking into it.

**Comment by vjuranek** [comment]
all tests passed with `s3`. 

Previous failures were caused due to some test buckets existed under different account. I also spot one minor issue (`s3` bucket name requirements seems to changes little bit), but I'll address it in separate PR.

**Comment by vjuranek** [comment]
> 'll address it in separate PR

done in #13

**Comment by tristantarrant** [comment]
Updated !

**Pull request merged**
